#+TITLE: La inteligencia artificial acaba de hacer en meses lo que a la arqueología le habría llevado décadas. Y está sacando a la luz secretos invisibles de uno de los mayores enigmas de la historia
#+OPTIONS: toc:nil num:nil

Buenos días.

El artículo [[https://es.gizmodo.com/la-inteligencia-artificial-que-esta-desvelando-secretos-invisibles-de-los-mayores-enigmas-de-historia-2000185643][«La inteligencia artificial acaba de hacer en meses lo que a la arqueología le habría llevado décadas. Y está sacando a la luz secretos invisibles de uno de los mayores enigmas de la historia»]] describe cómo las Líneas de Nazca, trazadas en el desierto del sur de Perú y visibles solo desde el aire, han resistido durante más de un siglo los intentos de los arqueólogos por comprenderlas plenamente, debido a su extensión y la dificultad de explorarlas.

Un equipo internacional entrenó un sistema de inteligencia artificial de IBM para analizar imágenes aéreas a gran escala. En seis meses, la herramienta detectó 303 geoglifos nuevos, duplicando los conocidos, y aportó indicios de que las figuras formaban parte de rutas rituales.

El éxito impulsa ahora la aplicación de esta tecnología en otros yacimientos arqueológicos del mundo. Aunque la IA aún necesita supervisión humana, su potencial para acelerar y ampliar la investigación promete revelar secretos históricos mucho antes de lo esperado.

Saludos, José A.

# Local Variables:
# eval: (visual-line-mode 1)
# End:
