#+TITLE: “Tendrán un 0”: cuatro autonomías blindan la Selectividad con detectores de frecuencia ante el aumento de alumnos que copian con la IA
#+OPTIONS: toc:nil num:nil

Buenos días.

El artículo [[http://archive.today/HQwCM][«“Tendrán un 0”: cuatro autonomías blindan la Selectividad con detectores de frecuencia ante el aumento de alumnos que copian con la IA»]] aborda la creciente preocupación por el fraude en las Pruebas de Acceso a la Universidad (PAU), impulsado por el avance de la tecnología y la inteligencia artificial. Las universidades detectan un aumento en el uso de dispositivos como nanopinganillos y calculadoras conectadas a la IA para copiar en los exámenes.

Ante esta situación, algunas comunidades autónomas están reaccionando implementando medidas para combatir el fraude. Galicia, Murcia, Cataluña y Aragón utilizarán detectores de frecuencia en la próxima convocatoria de la Selectividad, mientras que otras ocho regiones están considerando hacerlo.

La sanción para quienes sean descubiertos copiando es la anulación completa de la prueba. Las autoridades universitarias enfatizan la importancia de garantizar la igualdad de oportunidades y la credibilidad de las PAU, y advierten que la inversión en detectores de frecuencia puede ser significativa.

Saludos, José A.

# Local Variables:
# truncate-lines: t
# eval: (visual-line-mode 1)
# End:
