#+TITLE: ‘Magnifica humanitas’: el Papa León XIV publicará el día 25 su primera encíclica, dedicada a la IA
#+OPTIONS: toc:nil num:nil

Buenos días.

El artículo [[http://archive.today/xtgqQ][«‘Magnifica humanitas’: el Papa León XIV publicará el día 25 su primera encíclica, dedicada a la IA»]] informa de que León XIV publicará el 25 de mayo Magnifica humanitas, su primera encíclica, centrada en la protección de la persona humana en la era de la inteligencia artificial. Será el gran texto doctrinal inicial de su pontificado.

El artículo explica que el Papa presentará personalmente la encíclica en el Vaticano, acompañado por cardenales, teólogas y un representante de Anthropic. Ese formato rompe con la práctica reciente y refuerza la relevancia que León XIV concede a la inteligencia artificial.

El artículo sitúa el documento en continuidad con Rerum novarum y con la doctrina social de la Iglesia. León XIV quiere responder a la revolución digital como León XIII respondió a la industrialización y defender una IA sometida a límites éticos

Saludos, José A.

# Local Variables:
# truncate-lines: t
# eval: (visual-line-mode 1)
# End:
