#+TITLE: La tecnología suele crear puestos de trabajo para jóvenes cualificados. ¿_Hará lo mismo la IA?
#+OPTIONS: toc:nil num:nil

Buenos días.

El artículo [[https://news.mit.edu/2026/technology-creates-jobs-young-skilled-workers-ai-0521][«La tecnología suele crear puestos de trabajo para jóvenes cualificados. ¿Hará lo mismo la IA?»]] explora la relación entre tecnología y empleo en Estados Unidos, analizando cómo la innovación afecta al mercado laboral. Se plantea que, históricamente, la tecnología ha destruido empleos tradicionales a la vez que ha creado nuevas oportunidades, aunque estas últimas tienden a favorecer a un grupo demográfico específico: jóvenes graduados universitarios.

El estudio profundiza en los factores que impulsan la creación de nuevos empleos, destacando el papel de la demanda, especialmente la generada por inversiones públicas en investigación y manufactura. Se demuestra que la expansión industrial durante la Segunda Guerra Mundial fue un catalizador para la creación de nuevas especializaciones laborales.

Finalmente, el artículo aborda la incertidumbre sobre el impacto de la inteligencia artificial en el futuro del trabajo. Se argumenta que la forma en que se implemente la IA será determinante para crear o destruir empleos, y que la demanda pública puede influir en su aplicación para generar oportunidades en sectores clave como la salud.

Saludos, José A.

# Local Variables:
# truncate-lines: t
# eval: (visual-line-mode 1)
# End:
