#+TITLE: ¿Cuáles son los protagonistas que impulsan la IA en España?
#+OPTIONS: toc:nil num:nil

Buenos días.

El artículo [[http://archive.today/rQIUX][«¿Cuáles son los protagonistas que impulsan la IA en España?»]] presenta el panorama actual de la Inteligencia Artificial en España, señalando la existencia de un ecosistema vibrante con alrededor de 450 empresas emergentes. Se introduce a Multiverse Computing como la compañía más grande del sector, con una facturación considerable y aspiraciones de alcanzar una valoración superior a los mil millones de euros gracias a una nueva ronda de inversión.

A continuación, se detallan los proyectos de Cala AI, una startup fundada por una emprendedora con experiencia en Apple, y de Openchip, que busca liderar la industria europea de microchips con el apoyo de fondos públicos y privados. Ambas empresas están en fase de expansión y desarrollo tecnológico.

Finalmente, comenta el caso de Biorce, una startup portuguesa con sede en Barcelona que está revolucionando el sector de los ensayos clínicos con soluciones de IA. Su rápido crecimiento y la reciente ronda de inversión demuestran el potencial de la innovación española en este campo.


Saludos, José A.

# Local Variables:
# truncate-lines: t
# eval: (visual-line-mode 1)
# End:
