#+TITLE: El robot humanoide barato que puedes entrenar para que haga lo que tú quieras
#+OPTIONS: toc:nil num:nil

Buenos días.

El artículo [[https://www.elconfidencial.com/tecnologia/novaceno/2026-05-24/robotica-humanoides-batato-investigacion-inteligencia-artificial_4360006/][«El robot humanoide barato que puedes entrenar para que haga lo que tú quieras»]] describe el lanzamiento de DOMO, un robot humanoide desarrollado por la startup Rotaku en Silicon Valley. Esta propuesta destaca por su precio de 2.500 euros, una cifra muy inferior a los modelos de grandes corporaciones. El objetivo es facilitar el acceso ciudadano a la robótica avanzada.

El ingeniero Zhuoran Lu lideró el desarrollo del prototipo durante un año de trabajo discreto. Su equipo combina conocimientos de inteligencia artificial, control de movimiento y diseño industrial. Actualmente, la empresa ya acepta pedidos anticipados mientras gestiona nuevas rondas de financiación para asegurar la viabilidad del proyecto técnico.

El futuro de este robot depende de superar los retos logísticos de la producción en serie. Si Rotaku logra fabricar a gran escala, transformará el mercado tecnológico global. El dispositivo promete entrenarse según las necesidades del usuario, marcando un punto de inflexión en la industria de los androides comerciales.

Saludos, José A.

# Local Variables:
# truncate-lines: t
# eval: (visual-line-mode 1)
# End:
